### ISSUE TITLE
DOC: MCA argument. Contingency table or raw observations?

### ISSUE THREAD

**Issue by TomAugspurger** [MaxHalford/Prince#1]
In https://github.com/MaxHalford/Prince/blob/a854849c9e1ee2b331bb0fd4f0f939b1c01b0f01/prince/mca.py#L13 it says that `MCA` takes a dataframe that's a contingency table. From the examples (like `mca-ogm.py`) it looks like `MCA` takes the actual N obs x K variables DataFrame, not the summarized contingency table. Or I could be confused.

Overall, this looks great! One code comment: in places like [here](https://github.com/MaxHalford/Prince/blob/a854849c9e1ee2b331bb0fd4f0f939b1c01b0f01/prince/mca.py#L55) where you're filtering by dtype, you might be able to use [`DataFrame.select_dtypes`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.select_dtypes.html#pandas.DataFrame.select_dtypes).

**Comment by MaxHalford** [comment]
Hey,

In 

> https://github.com/MaxHalford/Prince/blob/a854849c9e1ee2b331bb0fd4f0f939b1c01b0f01/prince/mca.py#L13 it says that MCA takes a dataframe that's a contingency table. From the examples (like mca-ogm.py) it looks like MCA takes the actual N obs x K variables DataFrame, not the summarized contingency table. Or I could be confused.

You are right, the comment was bad; I just fixed.

> Overall, this looks great! One code comment: in places like here where you're filtering by dtype, you might be able to use DataFrame.select_dtypes.

I didn't know about this, it's great! It's being used now :)
