### ISSUE TITLE
Colorization missing from mca.plot_coordinates

### ISSUE THREAD

**Issue by Stevod** [MaxHalford/prince#100]
When I plot_coordinates, all the column variables appear in the same blue color, instead of different colors.

When I look at the code for plotting rows, I see:
` if show_row_points:
                ax.scatter(
                    row_coords.iloc[:, x_component],
                    row_coords.iloc[:, y_component],
                    s=row_points_size,
                    label=None,
                    color=plot.GRAY['dark'],
                    alpha=row_points_alpha
                )
`
However in the corresponding code for the column vars, the color is not explicitly set, and seems to default to blue for all prefixes:
` for prefix in prefixes.unique():
                mask = prefixes == prefix

                if show_column_points:
                    ax.scatter(x[mask], y[mask], s=column_points_size, label=prefix)`

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
