### ISSUE TITLE
Incorrect constant in Benzecri correction

### ISSUE THREAD

**Issue by simon-m** [MaxHalford/prince#103]
The constant K in set to `len(self.col_masses)` in [ca.py#L95](https://github.com/MaxHalford/prince/blob/master/prince/ca.py#L95) which is equal to the number of columns of the dummified dataframe.
According to [the SAS documentation](https://support.sas.com/documentation/cdl/en/statug/63347/HTML/default/viewer.htm#statug_corresp_sect021.htm) (section "MCA Adjusted Inertias") and [this paper](https://personal.utdallas.edu/~herve/Abdi-MCA2007-pretty.pdf) (section 5, p. 6), K should instead be equal to the number of "real" variables, i.e. columns before getting dummies.
Additionally, this correction only makes sense for MCA, not CA as far as I understood.

Another remark, because I am not sure whether to open a new issue about it.
The total inertia computed in [mca.py#L29](https://github.com/MaxHalford/prince/blob/master/prince/mca.py#L29) is not equal to the sum of (raw) eigenvalues even when `n_components` is equal to the number of columns (or even greater). For reference, see [this presentation](http://www.math.u-bordeaux.fr/~mchave100p/wordpress/wp-content/uploads/2013/10/ACM-M2.pdf) (slide 46) and [the SAS doc](https://support.sas.com/documentation/cdl/en/statug/63347/HTML/default/viewer.htm#statug_corresp_sect021.htm)(section "Statistics That Aid Interpretation", paragraph 2).
I honestly cannot really wrap my head around the definitions m - p (presentation), (m - p) / p (yours), and the sum of eigenvalues (SAS; also the easiest to make sense of since the relative contributions the eigenvalues sum to 1 by definition).

Regards

**Comment by flacoste** [comment]
PR #120 fixes these issues.

**Comment by MaxHalford** [comment]
*Meta: you can add a comment `closes #pr_number` anywhere in a pull request to automatically close an issue. Cool right?*

**Comment by flacoste** [comment]
Good to know! (You might want to close the issue as I didn't use that trick, and can only comment on the issue.)
