### ISSUE TITLE
use column_principal_components instead of row_principal_components

### ISSUE THREAD

**Issue by SadafGharaati** [MaxHalford/prince#113]
Hi,
Any Idea how can I use column_principal_components instead of row_principal_components. In the guideline of the package, it is mentioned  "The fit method is actually an alias for the row_principal_components method which returns the row principal components. However, you can also access the column principal components with the column_principal_components."

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
