### ISSUE TITLE
Transform breaking down due to dimensionality

### ISSUE THREAD

**Issue by msalem7777** [MaxHalford/prince#116]
Same as https://github.com/MaxHalford/prince/issues/56

The issue is showing up again in 0.7.1

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
