### ISSUE TITLE
Apply MCA to another Dataset to Predict the values 

### ISSUE THREAD

**Issue by Magic-fan** [MaxHalford/prince#118]
Hello, 

I was wondering if you could help me with my problem.

How can I apply my fitted MCA to another dataset and predict the values on the axes? 

Thanks in advance

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
