### ISSUE TITLE
Bug in formula to scale columns to unit variance in MFA, FAMD

### ISSUE THREAD

**Issue by christophe-williams** [MaxHalford/prince#119]
https://github.com/MaxHalford/prince/blob/988f7fe01b6e4c9476517d1939f5fe0e13deb158/prince/mfa.py#L97
https://github.com/MaxHalford/prince/blob/988f7fe01b6e4c9476517d1939f5fe0e13deb158/prince/mfa.py#L119

Both _prepare_input and _build_X_global try to scale columns to unit variance. However there is an error in both functions - they use .sum() instead of .mean() in the scaling formula.

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
