### ISSUE TITLE
biplot using FAMD

### ISSUE THREAD

**Issue by valentynbez** [MaxHalford/prince#124]
Hello, 
I think biplots are very informative for PCA. Therefore, I tried to plot "loading scores" of FAMD. 
Therefore I took column correlations, scaled them by (max - min) on the axis and plotted them on the original plot.

1. I am not sure if loading scores for PCA are the same as column correlations for FAMD
2. It would be nice to introduce an argument for plotting loading scores for selected variables 
![image](https://user-images.githubusercontent.com/61702053/148104898-442021b2-4982-4e77-9537-c8c7ad5836fe.png)

**Comment by FredLaRosa** [comment]
I try to make the same with my pca, how did you succeed to plot this?

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
