### ISSUE TITLE
AttributeError: module 'prince' has no attribute 'FAMD'

### ISSUE THREAD

**Issue by demongolem-biz** [MaxHalford/prince#126]
When I install from pip, I get v 0.7.1.  When I do:

`famd = prince.FAMD(n_components=2, n_iter=3,...`

I get the AttributeError: module 'prince' has no attribute 'FAMD' error.

**Comment by koeunlim** [comment]
There's another package called prince (bioinformatics or some sort). You can check the content with dir(prince) and see if famd.py is in the package directory. You can also locate the file location to check the package info and contents.
