### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by slittle-twilio** [MaxHalford/prince#127]
For `famd.column_correlations(X)`, I'm getting an error `TypeError: '<' not supported between instances of 'str' and 'int'`. The `fit` and `transform` methods work fine.

Removing `.sort_index()` in the `column_correlations` method of the `MFA` class seems to solve the issue, but would this have unintended effects?

**Comment by slittle-twilio** [comment]
My environment is python 3.9.10, prince-0.7.0, pandas 1.4.1, numpy 1.22.3

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
