### ISSUE TITLE
col and row contributions as well as cos2 not working in correspondence analysis

### ISSUE THREAD

**Issue by noemifasties** [MaxHalford/prince#128]
row_contributions and col_contributions not functioning in the correspondence analysis portion. it says 'CA' object has no attribute 'row_contributions'
![ca issue](https://user-images.githubusercontent.com/104970884/166880756-5c02720f-2a70-428e-aa18-60a1611ff730.png)

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
