### ISSUE TITLE
FAMD transform ValueError on qualitative data

### ISSUE THREAD

**Issue by EldadTalShir** [MaxHalford/prince#141]
Hi all,

FAMD's transform raises a pandas ValueError on qualitative data. To reproduce:

`df = pd.DataFrame(data=[['i',1,'n'],['ii',2,'n'],['iii',3,'y']],
                            columns=['a','b','c'])`
`dimred = prince.FAMD(n_components=2,random_state=1,engine='sklearn')`
`fitted = dimred.fit(df)`
`fitted.transform(df)`

I have tried using fitted.row_coordinates(df) instead but the results differ from those obtained via transform previously on the same dataset.

Would appreciate any input/advice on this!

**Comment by MaxHalford** [comment]
Hey @EldadTalShir! Nice one, you caught a bug. I forgot to check FAMD's transform method. I've fixed the issue and added unit tests so this doesn't happen again. You can download the latest version (0.8.3) to get this fix.

Thanks for opening the issue 🙏
