### ISSUE TITLE
'MCA' object has no attribute '_check_is_fitted' with .transform

### ISSUE THREAD

**Issue by luesibuesi** [MaxHalford/prince#143]
Hello there,

When using version 0.10.0 and calling the .transform function (after having fitted the data), I'm getting the following error message:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15244\3214519674.py in <module>
----> 1 mca_nn_svd = mca_nn.transform(X_tr_val_bin)

~\Anaconda3\envs\adsml\lib\site-packages\prince\mca.py in transform(self, X)
     49     def transform(self, X):
     50         """Computes the row principal coordinates of a dataset."""
---> 51         self._check_is_fitted()
     52         if self.check_input:
     53             utils.check_array(X, dtype=[str, np.number])

AttributeError: 'MCA' object has no attribute '_check_is_fitted'

Has anyone come across the same issue?

**Comment by Witzerl** [comment]
Yap same problem here!
