### ISSUE TITLE
Sklearn GridSearchCV: 'MCA' object has no attribute 'set_params'

### ISSUE THREAD

**Issue by luesibuesi** [MaxHalford/prince#145]
Hi Max,

I'm trying to run GridSearchCV using sklearn pipeline to see how many principal components I should best keep in my model, but I run into the error message that _'MCA' object has no attribute 'set_params'_.

Is that something that might be easily added to the package?

Thanks!

**Comment by MaxHalford** [comment]
Hey there! Yes I think so. That's a good use case. Let me get back to you soon.

**Comment by MaxHalford** [comment]
Hey @luesibuesi. I've published version 0.10.3. I made MCA inherit from sklearn base classes. Can you let me know if this work for you?

**Comment by luesibuesi** [comment]
Thank you, seems to work!
