### ISSUE TITLE
Information regarding Inverse MCA

### ISSUE THREAD

**Issue by ssatyendras** [MaxHalford/prince#148]
Hello,
I am looking for inverse transforms for MCA. 
I noticed there is an inverse transform implementation for PCA.
Do you plan to implement an inverse MCA transform?

Thanks & Regards,
Siva

**Comment by MaxHalford** [comment]
Hey there! It's not in the books, no. I wouldn't really know how to proceed without doing some research. I'll add it to my backlog, but I can't make promises on when.

**Comment by ssatyendras** [comment]
Thanks.
