### ISSUE TITLE
MCA: plotting assumes raw dataset has already run get_dummies

### ISSUE THREAD

**Issue by mabounassif** [MaxHalford/prince#149]
When trying to plot the same raw data after fitting, there's a key error that show that dummy columns are not in the list of columns

**Comment by mabounassif** [comment]
```python
mca = prince.MCA(
    n_components=3,
    n_iter=3,
    copy=True,
    check_input=True,
    engine='sklearn',
    random_state=42)
    
mca.fit(dataset_df)
mca.plot(dataset_df.iloc[:4999], x_component=0, y_component=1)
```

Error:
```
KeyError: '["(151.0, \'4101\', \'4\')_1.0", "(184.0, \'4030\', \'4\')_1.0"
```

**Comment by MaxHalford** [comment]
Hey 👋

Do you have a dataset I could reproduce this with?

**Comment by MaxHalford** [comment]
It's a bit tricky to fix to be honest. I'm not sure that's it's really correct to apply an MCA to a subset of a dataframe, after fitting the MCA. Are you basically looking to display a plot on a sample of the data?

**Comment by mabounassif** [comment]
Hey there! 

I'm trying to plot the labels along the first two components to make sense of the quality of the MCA.
I had to take the first 4999 because of the charting library limit.

I feel we are almost talking about the same thing but not quite.

**Comment by mabounassif** [comment]
Something like the plot_coordinates in this https://stackoverflow.com/questions/48521740/using-mca-package-in-python

**Comment by MaxHalford** [comment]
Ok, gotcha. I will look into this, but I can't promise when. In the meantime, I would recommend building your own chart with matplotlib, or some other charting tool 😕

**Comment by mabounassif** [comment]
No worries! I can also propose a PR if I find some nifty and clean way to do it.
Thanks for looking into this :)
