### ISSUE TITLE
UserWarning "pandas.DataFrame with sparse columns found" when running famd()

### ISSUE THREAD

**Issue by normanius** [MaxHalford/prince#152]
Dear princes!

I've noticed a warning when executing the below code using `famd()`. Find [attached](https://github.com/MaxHalford/prince/files/11604593/pip-packages.txt) the list of installed packages. I'm running MacOS 12.6, Python 3.10.5, and Prince 0.10.4. scikit-learn is also up-to-date (1.2.2).

I've noticed the exact same warning in the docs of [`famd()`](https://maxhalford.github.io/prince/famd/)!

Any significance to this warning? How to avoid it?

```python
import prince

dataset = prince.datasets.load_beers().head(1000)
dataset.head()

famd = prince.FAMD(
    n_components=2,
    n_iter=3,
    copy=True,
    check_input=True,
    random_state=42,

    engine="sklearn",
    handle_unknown="error"  # same parameter as sklearn.preprocessing.OneHotEncoder
)
famd = famd.fit(dataset)
```

Thanks for checking this issue.

[pip-packages.txt](https://github.com/MaxHalford/prince/files/11604593/pip-packages.txt)

**Comment by MaxHalford** [comment]
Good catch, just fixed it. I've also shipped a version, `0.10.5`.
