### ISSUE TITLE
How to transform on new unseen test data?

### ISSUE THREAD

**Issue by tricha-zemoso** [MaxHalford/prince#161]
I am able to fit the MCA model to training data. I would like to use the model then to find the row coordinates of new unseen data. The transform function is not working for unseen data as I get a keyerror. Is it possible to "transform" new data using model fitted to training data, like the sklearn transformation functions?
Please help me to understand.

**Comment by MaxHalford** [comment]
Hello. Can you provide a reproducible example?

**Comment by tricha-zemoso** [comment]
[data.csv](https://github.com/MaxHalford/prince/files/12141876/data.csv)
Python Code:

from prince import MCA
import pandas as pd

data = pd.read_csv("data.csv", index_col=[0])
mca = MCA(n_components=10, n_iter=3, copy=True, check_input=True, engine='sklearn',random_state=42)
mca = mca.fit(data[:3])
print(mca.eigenvalues_summary)
print(mca.row_coordinates(data[:3]))
print(mca.transform(data[3:]))
