### ISSUE TITLE
CA.row_coordinates only works with pd.DataFrame

### ISSUE THREAD

**Issue by lenafm** [MaxHalford/prince#163]
Hi Max, 

I've just been playing around with the CA class and I realised that CA.fit(X) accepts X to be a numpy array but when one tries to get CA.row_coordinates(X) with X being a numpy array it raises an error because it expects X to be a pd.DataFrame.

Not sure if this is a priority but I thought I'd let you know :)

**Comment by MaxHalford** [comment]
Thanks, that's a good remark. Actually, I never tested running the classes with numpy arrays. I think it makes sense to raise an error in that case. What do you think, kind stranger?

**Comment by MaxHalford** [comment]
Actually, prince could simply convert the array to a dataframe, and then output an array if an array was provided. It shouldn't be difficult to put in place. I'll update this issue when I'm done :)

**Comment by MaxHalford** [comment]
In the end I actually went with raising an error when an array is passed instead of a dataframe. Dataframes are now required in the new version (0.12.0). It's simpler this way, and more obvious for users.

Thanks for opening this issue @lenafm!
