### ISSUE TITLE
MCA doesn't work with column transformers of sklearn

### ISSUE THREAD

**Issue by MdotO** [MaxHalford/prince#167]
Hi,
     I would like to report this issue. Whenever I try fitting the MCA transformer being encapsulated in a column transformer, I get the error :
TypeError: 'MCA' object is not iterable

Here's a minimal reproducible code snippet:
```import numpy as np
import pandas as pd
from prince import MCA
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

df = pd.DataFrame(np.random.random((200,20)))
mca = MCA()
c = ColumnTransformer(['mca_cat', mca, list(range(10))])
# pipe = Pipeline([('mca_test', mca)])
# pipe.fit(df)
c.fit(df)
```
In the above code, the pipeline fit works fine but if I use column fit then it gives the above error. If I use column transformer and then encapsulate it in a pipe, the error remains the same

**Comment by MaxHalford** [comment]
Hey there. I believe the input to `ColumnTransformer` should be a list of tuples. You only passed a list. This code works for me:

```py
import pandas as pd
from prince import MCA
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import numpy as np

df = pd.DataFrame(np.random.random((200,20)))
mca = MCA()
c = ColumnTransformer([('mca_cat', mca, list(range(10)))])
# pipe = Pipeline([('mca_test', mca)])
# pipe.fit(df)
c.fit(df)
```

**Comment by OmerPNW** [comment]
Oof. Should have debugged and looked a bit more before reaching to a conclusion.
Thanks a lot !!!

**Comment by MdotO** [comment]
Oof. Should have a looked and debugged a bit more before reaching prematurely to this conclusion
Thanks a lot !!!
