### ISSUE TITLE
mca.plot_rows_columns labeling and colorbar ticks are inconsistent

### ISSUE THREAD

**Issue by TomAugspurger** [MaxHalford/Prince#2]
This script

```python
import numpy as np
import prince
import pandas as pd
import matplotlib.pyplot as plt


s = pd.DataFrame({
    'A': pd.Categorical(np.random.choice(list('abcde'), size=(1000,)),
                        categories=['e', 'd', 'c', 'a', 'b']),
    'C': pd.Categorical(np.random.choice(list('abcde'), size=(1000,)),
                        categories=['e', 'd', 'c', 'a', 'b']),
    'B': pd.Categorical(np.random.choice(list('abcde'), size=(1000,)),
                        categories=['e', 'd', 'c', 'a', 'b']),
})
mca = prince.MCA(s)
fig, ax = mca.plot_rows_columns(show_column_labels=True)

plt.savefig('cat_label_bug.png')
```

Produces this figure

![cat_label_bug](https://cloud.githubusercontent.com/assets/1312546/20542242/6a456bc6-b0c6-11e6-870c-413b4b453633.png)

It looks like the annotations and the tick labels are inconsistent with each other (I'm guessing one goes in column order, while the other is alphabetical). I haven't dug into whether it's the annotations or the tick labels that are wrong.

**Comment by MaxHalford** [comment]
Hello, sorry I couldn't get to you earlier.

You're right! I looked into and it seems that I forgot to sort the keys obtained during groupby operations. It's all sorted now 👍 

Thanks again.

**Comment by TomAugspurger** [comment]
Thanks!
