### ISSUE TITLE
Large sparse matrices and MemoryError

### ISSUE THREAD

**Issue by LauriTK** [MaxHalford/prince#20]
Hi, I am trying to use Prince MCA for Dorothea dataset. I ran to MemoryError at calculating the standardised residuals with np.diag(). Is it possible to substitute np.diag() with scipy.sparse.npdiags which works with sparse matrices? Like this 'S = diags(r ** -0.5) @ (X - np.outer(r, c)) @ diags(c ** -0.5)' ? With this modification the code runs and results are somewhat same with minor differences. Any insight on problems of using scipy's diags?

**Comment by MaxHalford** [comment]
Hey,

Using scipy isn't a problem as it's a pandas dependencies anyway. Would you mind submitting a pull request or do you want me to take care of this?

**Comment by LauriTK** [comment]
Go ahead, I am not able to test it thoroughly if it breaks something. If you're interested, esafak used also this scipy.sparse.diags. https://github.com/esafak/mca

**Comment by MaxHalford** [comment]
Version 0.3.7 now uses `scipy.sparse.npdiags` instead of `np.diag`.

**Comment by LauriTK** [comment]
Thanks! Will test this. Btw, sorry it's scipy.sparse.diags, had typo.

This could be nice addon on the SVD engine side. I will try it someday. https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html
