### ISSUE TITLE
Two potential issues with MFA.py

### ISSUE THREAD

**Issue by danielxwang90** [MaxHalford/prince#22]
(I'm a novice at Python so apologies if these are not correct observations)

1. In MFA.py, in line 55, 'all_num' is static since it is set in a prior loop in line 50. Should you either add 'all_num = all_nums[name]' or merge the two loops (line 45 and line 54)?

2. On line 88, you have "X[cols] / self.partial_factor_analysis_[name].s_[0]", but it does not seem to work with categorical pandas dataframes as X[cols] is not numeric and cannot be divided by a scalar

**Comment by MaxHalford** [comment]
Hey!

You're right on both points. I just fixed them. Thank you so much for opening the issue.

Regards.
