### ISSUE TITLE
Global PCA in MFA for categorical fields

### ISSUE THREAD

**Issue by danielxwang90** [MaxHalford/prince#23]
Thanks for fixing the previous issue so quickly. There seems to still be an issue with line 76 in MFA.py when "super().fit(self._build_X_global(X))" is running the .fit() for PCA:
- For categorical groups, _build_X_global retains the columns as they are (line 90 in MFA.py)
- However, line 40 of PCA.py (within the .fit() method) and below assumes the dataframe is numeric

You can recreate the issue by using the sample data (and ignoring the scaling):
X = pd.DataFrame(
     data=[
         ["A", "A", "A", 2, 5, 7, 6, 3, 6, 7],
         ["A", "A", "A", 4, 4, 4, 2, 4, 4, 3],
         ["B", "A", "B", 5, 2, 1, 1, 7, 1, 1],
         ["B", "A", "B", 7, 2, 1, 2, 2, 2, 2],
         ["B", "B", "B", 3, 5, 6, 5, 2, 6, 6],
         ["B", "B", "A", 3, 5, 4, 5, 1, 7, 5]
     ],
     columns=['E1 fruity', 'E1 woody', 'E1 coffee',
              'E2 red fruit', 'E2 roasted', 'E2 vanillin', 'E2 woody',
              'E3 fruity', 'E3 butter', 'E3 woody'],
     index=['Wine {}'.format(i+1) for i in range(6)]
 )

Thanks!

**Comment by MaxHalford** [comment]
This is now fixed with version 0.4.3.
