### ISSUE TITLE
FAMD doesn't work on Wine Data

### ISSUE THREAD

**Issue by ttpostle** [MaxHalford/prince#27]
I'm attempting to use FAMD on the Wine Data, which is all numeric. (As I don't see an example for FAMD -- this would be very helpful!) 

Trying to fit the FAMD results in a Value Error

`import prince
import pandas as pd

X = pd.DataFrame(
    data=[
        [1, 6, 7, 2, 5, 7, 6, 3, 6, 7],
        [5, 3, 2, 4, 4, 4, 2, 4, 4, 3],
        [6, 1, 1, 5, 2, 1, 1, 7, 1, 1],
        [7, 1, 2, 7, 2, 1, 2, 2, 2, 2],
        [2, 5, 4, 3, 5, 6, 5, 2, 6, 6],
        [3, 4, 4, 3, 5, 4, 5, 1, 7, 5]
    ],
    columns=['E1 fruity', 'E1 woody', 'E1 coffee',
            'E2 red fruit', 'E2 roasted', 'E2 vanillin', 'E2 woody',
            'E3 fruity', 'E3 butter', 'E3 woody'],
    index=['Wine {}'.format(i+1) for i in range(6)]
)

famd = prince.FAMD()
famd.fit(X)`

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-52-bb0232372498> in <module>()
     18 
     19 famd = prince.FAMD()
---> 20 famd.fit(X)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\famd.py in fit(self, X, y)
     35 
     36         # One-hot encode the categorical columns
---> 37         self.one_hot_ = one_hot.OneHotEncoder().fit(cat)
     38 
     39         # Apply PCA to the indicator matrix

~\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\one_hot.py in fit(self, X, y)
    152             raise ValueError('X must be a pandas.DataFrame')
    153 
--> 154         self = super().fit(X)
    155         self.column_names_ = list(itertools.chain(*[
    156             [

~\AppData\Local\Continuum\anaconda3\lib\site-packages\prince\one_hot.py in fit(self, X, y)
     51                                      "supported")
     52 
---> 53         X_temp = utils.check_array(X, dtype=None)
     54         if not hasattr(X, 'dtype') and np.issubdtype(X_temp.dtype, np.str_):
     55             X = utils.check_array(X, dtype=np.object)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py in check_array(array, accept_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    468                              " a minimum of %d is required%s."
    469                              % (n_features, shape_repr, ensure_min_features,
--> 470                                 context))
    471 
    472     if warn_on_dtype and dtype_orig is not None and array.dtype != dtype_orig:

ValueError: Found array with 0 feature(s) (shape=(6, 0)) while a minimum of 1 is required.`

**Comment by MaxHalford** [comment]
This is now fixed with version 0.4.3.
