### ISSUE TITLE
back to py2

### ISSUE THREAD

**Issue by bibile** [MaxHalford/prince#28]
Hi,

I would need to have Prince working with python2. too bad ...
I saw that the @ operator is not supported in py2. like in ca.py
`data=X @ sparse.diags(self.row_masses_ ** -0.5) @ self.U_`

I am not familiar with that @.
Is it possible to rewrite it using np.matmul?
Like
`data=np.matmul(np.matmul(X, sparse.diags(self.row_masses_ ** -0.5)), self.U_)`

I looked into going back to an old version, but I am using it also in py3, and like the way it works now.

**Comment by MaxHalford** [comment]
Sorry but Python 2 won't be supported.
