### ISSUE TITLE
FAMD modifies original DataFrame

### ISSUE THREAD

**Issue by r0f1** [MaxHalford/prince#29]
Hi,
As it says in the title already, FAMD modifies original DataFrame.

Example:
```Python
df = pd.DataFrame(
    data=[
        [1, 1, 1, 2, 5, 7],
        [1, 1, 1, 4, 4, 4],
        [2, 1, 2, 5, 2, 1],
        [2, 1, 2, 7, 2, 1],
        [2, 2, 2, 3, 5, 6],
        [2, 2, 1, 3, 5, 4]
    ]
)
for c in range(3):
    df[c] = df[c].astype("object")
famd = FAMD(
    n_components=3,
    n_iter=3,
    copy=True,
    engine='auto',
    random_state=4
)
famd = famd.fit(df)
famd_result = famd.transform(df)
```
`famd_result` contains the result (as expected).
`df` however was modified. My current workaround copies the DataFrame, before passing it to `fit()` and `transform()`.

Is this modification of `df` intended?

![image](https://user-images.githubusercontent.com/7324891/43897444-46c1e3e8-9bdc-11e8-9804-17f1f1950961.png)

**Comment by MaxHalford** [comment]
Nice catch, just fixed it in 0.4.6.

I have to write more unit tests!
