### ISSUE TITLE
Mistake in examples documentation

### ISSUE THREAD

**Issue by Guilherme-Routar** [MaxHalford/prince#30]
There is a mistake in the examples documentation for FAMD. The following line

`famd = mfa.fit(X.drop('Oak type', axis='columns'))  # No need for 'Oak type'`

should be

`famd = famd.fit(X.drop('Oak type', axis='columns'))  # No need for 'Oak type'`

_mfa_ is used on the _famd_ example

**Comment by MaxHalford** [comment]
Thanks a lot, I just fixed it.
