### ISSUE TITLE
Contributing to prince

### ISSUE THREAD

**Issue by RohanVardhan** [MaxHalford/prince#33]
Is there any way I can contribute to the project? I use this package a lot and I have added methods which I would like to be part of the original package.

**Comment by MaxHalford** [comment]
I'm not sure why you closed this but fair enough. Help would be greatly appreciated; what methods do you have in mind?

**Comment by RohanVardhan** [comment]
I had not checked CONTRIBUTION.md file when I raised this issue. Anyway, the data that I use is mixed. So I want to know the column correlations when I perform FAMD, which is why I had created a method for that. I was hoping to push to the repo, but there was a permissions issue, I guess.

**Comment by MaxHalford** [comment]
You can't directly push to the repo. You have to open a branch, push your code to the branch, and then make a pull request.

**Comment by RohanVardhan** [comment]
@MaxHalford , will do that!

**Comment by MaxHalford** [comment]
Hey there,

I integrated your changes myself, the changes are taken into account from now on (version `0.4.7`). Thanks a lot for the PR, it helped. In the future please pull a branch from this repository, this will make it possible for me (and others) to edit your branch and fix stuff.

Regardless, thanks a lot. I appreciate your help.

**Comment by RohanVardhan** [comment]
Hi @MaxHalford . Sorry about that. I had created my branch, but was not able to push to that branch (maybe because of permissions issue). That's why I had to fork and send PR.

**Comment by RohanVardhan** [comment]
Thanks for integrating the feature!!
