### ISSUE TITLE
Chi square distances

### ISSUE THREAD

**Issue by DemirTonchev** [MaxHalford/prince#37]
Is there a way to get the chi square distances in CA between rows, like in formula (17.18) from Izenman book?

**Comment by MaxHalford** [comment]
There is, but I would have to look into it. Pull requests are appreciated :))

**Comment by DemirTonchev** [comment]
I was looking in ca.py but could not find it explicitly. Let me know if/how I can help.

**Comment by MaxHalford** [comment]
That's because I haven't implemented it, yet. If you can show me an equation or some pseudo-code then I can implement it.

**Comment by MaxHalford** [comment]
Any update @DemirTonchev ?
