### ISSUE TITLE
Calling fit on FAMD object with numerical data only gives ValueError exception

### ISSUE THREAD

**Issue by covuworie** [MaxHalford/prince#40]
**Observed behavior**: I used the example Iris dataset that is given in the documentation. Instead of creating a `PCA` object, I create a `FAMD` object. I call fit on it just like in the documentation and I get a Value error:

ValueError: Found array with 0 feature(s) (shape=(150, 0)) while a minimum of 1 is required.

Not sure exactly why this is happening.

**Expected behavior**: For purely numerical data (such as in the IRIS dataset) I would expect that the FAMD should produce identical results to the PCA. I see the documentation says to use PCA in this case. So I guess it's a matter of interpretation as to what the expected behavior should be. But at the least another exception saying use 'PCA for purely numerical data'. Anyway, please let me know your thoughts.

**Comment by RohanVardhan** [comment]
FAMD will not work if the data set contains only quantitative variables.

**Comment by MaxHalford** [comment]
Indeed FAMD should be equivalent to PCA if all the data is numerical. I'm looking into this edge-case now.

**Comment by MaxHalford** [comment]
Okay I've written a fix. It turns out that it doesn't make any sense to do an FAMD if you don't have both categorical data **and** numerical data. Fitting an `FAMD` to a dataset that doesn't contain both type will now raise a helpful `ValueError` that suggests to the user `MCA` or `PCA` (depending on the data).

**Comment by covuworie** [comment]
@MaxHalford  That sounds much better. Thanks.
