### ISSUE TITLE
Calling column_correlations on FAMD gives ValueError

### ISSUE THREAD

**Issue by covuworie** [MaxHalford/prince#41]
**Observed behavior**: Using the wine dataset example that is given in the documentation, I call `column_correlations` method of the FAMD object and get the following ValueError exception:

All the input array dimensions except for the concatenation axis must match exactly

Not sure exactly why this is happening.

**Expected behavior**: The column correlations to be returned since the shape of the X vector parameter passed into the method is (6, 10).

**Comment by MaxHalford** [comment]
I just fixed this! Thanks for creating the issue. The issue is that now we're using sparse data structures where we can and this doesn't always align well with numpy.

**Comment by covuworie** [comment]
Thanks very much for this @MaxHalford.

Great library btw! Wondering when you are planning to release a version of the library with this fix?

**Comment by MaxHalford** [comment]
Hey! And thanks!

If I'm not mistaken this is fixed with version 0.4.9.

**Comment by covuworie** [comment]
Hey thanks very much! I didn't realize you had already released a new version to pypi. I just tried it and the issue seems to be resolved.
