### ISSUE TITLE
ca.total_inertia_ > 1.0

### ISSUE THREAD

**Issue by bibile** [MaxHalford/prince#42]
Hi,

I was surprised to get a `ca.total_inertia_` equal to 1.45.
If I `np.sum(ca.explained_inertia_)`, I then get something very close to 1.

I though that 1 was supposed to be the correct answer, if we ask for a lot of components.
Am I misunderstanding something?

**Comment by MaxHalford** [comment]
Hey,

The `total_inertia` is simply the sum of the variances assigned to each component. The `explained_inertia` is a list of the **proportion** of variance assigned to each component. In other it is a percentage. `explained_inertia` is obtained by dividing each eigenvalue by `total_inertia`.

I hope this makes things clearer.

**Comment by bibile** [comment]
Hi,
Thanks a lot for clarifying this!
