### ISSUE TITLE
got multiple values for argument 'n_components'

### ISSUE THREAD

**Issue by sesam15** [MaxHalford/prince#46]
I was trying to run the CA.
I started by the 'presidentielles' example  and got this error: 

Traceback (most recent call last):

  File "<ipython-input-15-d6be162a1d44>", line 5, in <module>
    engine='auto'

TypeError: __init__() got multiple values for argument 'n_components'

**Comment by MaxHalford** [comment]
Hello,

Where exactly is the example you're looking at?

**Comment by sesam15** [comment]
I installed the package then I toke the presidentielles set to test it and I got this error

**Comment by MaxHalford** [comment]
I'm going to need more info than this... Can you please post the code you used? You understand that I can't just guess what the problem is without seeing what you're done.

**Comment by MaxHalford** [comment]
Closing this, feel free to reopen it if necessary.
