### ISSUE TITLE
Results have minor errors compared to step-by-step computation

### ISSUE THREAD

**Issue by YiChanLee** [MaxHalford/prince#5]
Hi, I tried to implement CA by myself and our results could not match. The principal coordinates and standard coordinates for both row and col always have a small numerical difference (around 7%, not like a round-off issue). 

I have been checking it a day and compared the computations of every steps. Except coordinates, all the rests are all matched (such as `row_masses`, `standardized_residuals`), and I couldn't see why the results not match. I cannot even reproduce the output by extract `row_masses`, `standardized_residuals` and do the multiplication myself.

Please check if the code can reproduce the hair-eye example at p.649 of following book (Alan J Izenman, Modern Multivariate Statistical Techniques) where more accurate (1e-4) results are provided.
http://ce.aut.ac.ir/~shiry/lecture/Advanced%20Machine%20Learning/Manifold_Modern_Multivariate%20Statistical%20Techniques%20-%20Regres.pdf

Great work! Looking forward to the development of FAMD part!

**Comment by MaxHalford** [comment]
Hello,

I'm going to look into this soon, I'm a bit busy at the moment. Thanks for the input!

**Comment by MaxHalford** [comment]
I've just refactored the entire codebase. In the process I reimplemented CA. The results I got were in accordance with the paper you mentioned. However I wouldn't follow their example religiously as they don't seem to provide any code.

I'm closing this issue but feel free to reopen it.
