### ISSUE TITLE
Error with FAMD

### ISSUE THREAD

**Issue by sharma-ji** [MaxHalford/prince#50]
So I am using the example given by you for FAMD, but I am getting and error 

`C:\ProgramData\Anaconda3\lib\site-packages\scipy\_lib\_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    239     if not objects_ok:
    240         if a.dtype is np.dtype('O'):
--> 241             raise ValueError('object arrays are not supported')
    242     if as_inexact:
    243         if not np.issubdtype(a.dtype, np.inexact):

ValueError: object arrays are not supported` 

My FAMD is 0.5.2, also I have tried converting objects in categories but still getting same error

**Comment by MaxHalford** [comment]
Okay I'll go check the issues with `pandas==0.24.0` and fix them.

**Comment by MaxHalford** [comment]
Okay I pushed version `0.6.0` which fixes the issue.
