### ISSUE TITLE
FAMD: TypeError: cannot concatenate object

### ISSUE THREAD

**Issue by Timonzimm** [MaxHalford/prince#51]
Hi!
While trying to fit `FAMD`: 
```python
famd = prince.FAMD(n_components=2, n_iter=3, copy=True, check_input=True, engine='auto')
famd = famd.fit(df)
```
Where `df` contains the following dtypes:
```
ip                     object
app                    object
channel                object
DAY(click_time)         int64
YEAR(click_time)        int64
MONTH(click_time)       int64
WEEKDAY(click_time)     int64
users.device           object
users.os               object
```

Tje object `df` seems to be of the right type: **<class 'pandas.core.frame.DataFrame'>** and its columns also, but I get the following error:
**TypeError: cannot concatenate object of type "<class 'scipy.sparse.csr.csr_matrix'>"; only pd.Series, pd.DataFrame, and pd.Panel (deprecated) objs are valid**

Does it look like something coming from my side? Or is it a known bug of the libray?

Best,

**Comment by MaxHalford** [comment]
Hello,

Can you please provide me with a working example of the dataset you're using? This could be due to the version of `pandas` but I don't know for sure.

Regards.

**Comment by Timonzimm** [comment]
Sure, here is the dataset I'm using, you have the types in the original post.

[df.csv.zip](https://github.com/MaxHalford/prince/files/2861493/df.csv.zip)

Thank you very much for your help!

**Comment by Timonzimm** [comment]
Here are the library versions I'm using:
* Pandas: 0.24.1
* Prince: 0.6.0

Best,

**Comment by MaxHalford** [comment]
Okay I fixed it :). It wasn't much. You can install the latest version which is `0.6.1` and you should be fine. I'll let you close this issue if everything is working on your side.

**Comment by Timonzimm** [comment]
Awesome thank you, it fixed the problem.
