### ISSUE TITLE
MCA not working(TypeError: __init__() got an unexpected keyword argument 'categories')

### ISSUE THREAD

**Issue by Tejas-Shanbhag** [MaxHalford/prince#52]
MCA() throws an error when using the fit() method on categorical dataframe.

**Comment by adeebabdulsalam** [comment]
> MCA() throws an error when using the fit() method on categorical dataframe.

Ya,but for me it worked initially.Then I just tried to find column principal components {mca.column_principal_components(X)} instead of row principal components(mca.fit(X)),but it didn't work.So i changed back to fit itself.Then this problem started

**Comment by MaxHalford** [comment]
Hey,

Can you provide a working example?

**Comment by adeebabdulsalam** [comment]
`import pandas as pd
import prince

data = pd.read_csv("data/training set.csv")
X = data.loc[:,'OS.1':'DSA.1']
size=len(X)
X=X.values.tolist()
def gradeval(grade):
    switcher={
        "S": 10,
        "A": 9,
        "B": 8,
        "C": 7,
        "D": 6,
        "E": 5,
        "R": 4,
        "F": 0,
    }
    return switcher.get(grade,"")

for i in range(0,size):
    for j in range(0,4):
        X[i][j]=gradeval(X[i][j])

df = pd.DataFrame(X)
df.columns = ['OS', 'Networks', 'DBMS', 'DSA']
mca = prince.MCA(
               n_components=2,
               n_iter=3,
               copy=True,
               check_input=True,
               engine='auto',
               random_state=42
                )
mca = mca.fit(df)
print(mca.eigenvalues_)`


#Output

 File "<location>", line 61, in <module>
    mca = mca.fit(df)
  File "<location>\lib\site-packages\prince\mca.py", line 25, in fit
    self.one_hot_ = one_hot.OneHotEncoder().fit(X)
  File "<location>\lib\site-packages\prince\one_hot.py", line 15, in __init__
    super().__init__(sparse=True, dtype=np.uint8, categories='auto')
TypeError: __init__() got an unexpected keyword argument 'categories'

**Comment by MaxHalford** [comment]
Can you tell what version of scikit-learn you're using?

**Comment by adeebabdulsalam** [comment]
> Can you tell what version of scikit-learn you're using?

0.19.2

**Comment by MaxHalford** [comment]
Yep normally the version of `prince` you're using should require that you have version 0.20.1 of scikit-learn installed. If you did `pip install prince` then this should have been done for you. Do `pip install --upgrade scikit-learn` and you should be good.

**Comment by Tejas-Shanbhag** [comment]
Okay thanks!!

**Comment by adeebabdulsalam** [comment]
> Yep normally the version of `prince` you're using should require that you have version 0.20.1 of scikit-learn installed. If you did `pip install prince` then this should have been done for you. Do `pip install --upgrade scikit-learn` and you should be good.

Yeah ,that worked.Thanks
