### ISSUE TITLE
Using FAMD for numerical and binary data

### ISSUE THREAD

**Issue by tfcoe** [MaxHalford/prince#54]
Hey,

I am working with a dataset with a combination of continuous (~35%) and binary variables (1/0 representing Y/N) (~65%). 

The binary variables were generated in a data preparation phase where I extracted information from categorical variables. They aren't strictly groups of dummy variables as there is some overlap.

My understanding is that PCA isn't fully appropriate here and using FAMD is the way to go, but since the data is already encoded as numerical variables the FAMD doesn't work. 

Looking at the underlying code it seems to split numerical and categorical columns into two separate "groups" then runs MFA on both. In order to get around the error thrown back can I just manually run MFA supplying the numerical and binary columns as separate groups?

**Comment by MaxHalford** [comment]
Hello,

I'm really sorry I didn't see this issue until now, my apologies.

PCA is applicable and should provide meaningful results, but indeed it isn't ideal.

Indeed you could use an MFA and split the variables into groups accordingly.
