### ISSUE TITLE
problem with FAMD

### ISSUE THREAD

**Issue by Mory1989** [MaxHalford/prince#55]
Hi , 
when I try to use FAMD to my mix dataset (contains continuous and categorical variables) an error message appears: 

**ValueError:** FAMD works with categorical and numerical data but you only have categorical data; you should consider using MCA

I'm sure I have mix data, but I don't know what is the problem !
any help please?

**Comment by MaxHalford** [comment]
What happens when you print `df.dtypes`? Can you provide a concrete example?

**Comment by Mory1989** [comment]
Thanks for your quick response

sorry, I am a beginner in python
 
when I try .dtypes() it does not work !!
Error: TypeError: 'Series' object is not callable

but when I use .Info() I got this:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 24 columns):
age      400 non-null int64
bp       400 non-null int64
sg       400 non-null object
al       400 non-null object
su       400 non-null object
rbc      400 non-null object
pc       400 non-null object
pcc      400 non-null object
ba       400 non-null object
bgr      400 non-null int64
bu       400 non-null float64
sc       400 non-null float64
sod      400 non-null int64
pot      400 non-null float64
hemo     400 non-null float64
pcv      400 non-null int64
wc       400 non-null int64
rc       400 non-null float64
htn      400 non-null object
dm       400 non-null object
cad      400 non-null object
appet    400 non-null object
pe       400 non-null object
ane      400 non-null object
dtypes: float64(5), int64(6), object(13)

**Comment by Mory1989** [comment]
Sorry for comment again 
but I just tried something and the error message has gone 👍 

maybe the problem because I use **df.values** to fit in **FAMD**
ie: 
famd = prince.FAMD().fit(df.values)
because I use this when I apply **PCA** using **sklearn.decomposition**

now I just change it to: 
famd = prince.FAMD().fit(df)
and no error message occurs 

so, what do you think?

**Comment by MaxHalford** [comment]
Yeah it's a bit hard to debug without a reproducible example. Can you share some code?

**Comment by Mory1989** [comment]
the function FAMD now works fine thank you 
but I have questions
1. Do I need to scale(normalize) variables before applying FAMD? or the scale will done automatically?
2.  is there a way to know the contribution of each column to the components? 
Thanks

**Comment by MaxHalford** [comment]
1. The scaling will be done automatically
2. In theory yes but I haven't implemented the possibility to do so yet

Cheers
