### ISSUE TITLE
MCA vs OneHot+SVD

### ISSUE THREAD

**Issue by buhrmann** [MaxHalford/prince#57]
Hi, not reporting a bug, but was just wondering if you could explain or point me to a reference on how MCA is different from just doing a one-hot encoding followed by SVD? From the code I can see that the difference is a normalization you apply to the onehot matrix first, but I'm not sure what the effect of this normalization is.

Also, would it makes sense to apply MCA or onehot+SVD to a single categorical column? Asking because in that case all the rows would be "orthogonal" and I'm not sure if any useful correlation/structure can be found in that case?

**Comment by MaxHalford** [comment]
Hey,

Indeed there is no magic: MCA is just a CA applied to the one-hot encoded version of the input dataset. The normalization is to help take into account that some categories appear more frequently than others, which can skew the results.

There isn't much sense in applying an MCA to a single column. Indeed the point is to capture interactions between variables. If you one-hot encode a single column then you get a dataset where there is only a single  `1` per row, so there are no interactions (as you say, the columns are orthogonal).

I hope this helped! I'm not sure if you've seen it but [here](https://core.ac.uk/download/pdf/6591520.pdf) is a nice resource on MCA (IMHO).

**Comment by buhrmann** [comment]
Thanks for the quick response! That all makes perfect sense. Thanks also for the link, looks like a useful reference indeed!
