### ISSUE TITLE
How to reconstruct the original data after MCA transformation

### ISSUE THREAD

**Issue by adeebabdulsalam** [MaxHalford/prince#58]
There is mca.eigenvalues_  which gives 2 values.
But [this page](https://stats.stackexchange.com/questions/229092/how-to-reverse-pca-and-reconstruct-original-variables-from-several-principal-com) mentions Eigen vectors are required to do that.But the Readme doesn't mention it.

**Comment by pollyannagoncalves-hotmart** [comment]
I'm looking for the same thing, but with FADM. Need to reconstruct my dataset but I couldn't see any inverse_transform similar function. Did you managed to do this?

**Comment by MaxHalford** [comment]
It's not a trivial thing to do for MCA and FAMD but it would be nice to have. I should have some time to this soon!

**Comment by joel-simon** [comment]
Inverse transform for MCA would be great :)
