### ISSUE TITLE
Docs depend on subdirectory ./source which does not exist

### ISSUE THREAD

**Issue by tfawcett** [MaxHalford/prince#6]
In ./docs subdirectory, Makefile references source directory to contain the Sphinx sources.  EG:

`ALLSPHINXOPTS   = -d $(BUILDDIR)/doctrees $(PAPEROPT_$(PAPER)) $(SPHINXOPTS) source
`
source subdir does not exist.

**Comment by MaxHalford** [comment]
This isn't an issue anymore as the project isn't using Sphinx anymore.
