### ISSUE TITLE
standardization/Normalization in FAMD

### ISSUE THREAD

**Issue by theanto** [MaxHalford/prince#60]
Ehy dear, 
I m looking in FAMD with Python. I will ask, in PCA is very important the standardization before compute the algorithm( https://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html ), but how to work in FAMD? Why we can't computer standardization before apply this one? The algorithm already done? If yes, how is done?  

Thanks.

**Comment by MaxHalford** [comment]
Hey there,

Indeed it's recommended to rescale the data before running a PCA; this is taken care of by `prince` through the use of the `rescale_with_mean` and `rescale_with_std` parameters. As for the FAMD you can use the `normalize` parameter which will take care of standardizing the numerical data. As an example check out [this paper](https://www.utdallas.edu/~herve/Abdi-MFA2007-pretty.pdf). Each of the 3 parameters I just mentioned are boolean.

Kind regards.

**Comment by theanto** [comment]
So in this part miss an attribute normalize and we can change this code

```
import prince
>>> famd = prince.FAMD(
...     n_components=2,
...     n_iter=3,
...     copy=True,
...     check_input=True,
...     engine='auto',
...     random_state=42
... )
>>> famd = famd.fit(X.drop('Oak type', axis='columns'))
```

Because i tried to add an attribute asu you suggest in this list 

```
import prince
>>> famd = prince.FAMD(
...     n_components=2,
...     n_iter=3,
...     copy=True,
...     check_input=True,
...     engine='auto',
       normalize= True,
...     random_state=42
... )
>>> famd = famd.fit(X.drop('Oak type', axis='columns'))
```

But don't work. Bye the way this normalize will be work on numeric, because MCA alrady normalize for quantifier, like as say in a pdf that you link me, right? So in FAMD we just normalize "PCA" part.

By the way, thanks for fast reply and for this big and good work.

**Comment by MaxHalford** [comment]
Sorry my bad: normalization is automatically used for `FAMD`; it's optional for `MFA`. Yes you're right, we just normalize the PCA part.

Cheers! Always a pleasure.

**Comment by SadafGharaati** [comment]
Hi, I have the same issue when using FAMD in python, how should I normalize PCA section when using FAMD?
