### ISSUE TITLE
Unreliable results while FAMD model is returned from a function.

### ISSUE THREAD

**Issue by babinu-uthup-4JESUS** [MaxHalford/prince#61]
Hi,

I did notice that when you return the FAMD transform object from a function, the next results are sometimes unreliable. The following code snippet elucidates the issue :

```python
import prince
import pandas as pd
from sklearn import linear_model
cv_train = pd.read_csv('cv_training3.csv')
famd = prince.FAMD(
    n_components=25,
    n_iter=10,
    copy=True,
    check_input=True, 
    engine='auto',
    random_state=42)
x_cols = [col for col in cv_train.columns if col != 'LogSalePrice']
print(x_cols)

X = cv_train[x_cols]
famd_model = famd.fit(X)
transformed_X = famd_model.transform(X)

my_model = linear_model.LinearRegression()
my_model.fit(transformed_X, cv_train['LogSalePrice'].values.ravel())

cv_validation = pd.read_csv('cv_validation3.csv')

old_predictions = my_model.predict(transformed_X)
print(old_predictions.mean())

new_X = cv_validation[x_cols]

new_transformed_X = famd_model.transform(new_X)

new_predictions = my_model.predict(new_transformed_X)
print(new_predictions.mean())
```
We have the following output : 

```
['MSSubClass', 'LogGrLivArea', 'MSZoning']
12.030180212569563
-2158687260190.6848
```

Now consider the following code snippet : 

```python
import pandas as pd
import prince
from sklearn import linear_model

def get_trained_model_and_transform(X, Y, num_components=25, num_iter=20):
    famd = prince.FAMD(
        n_components=num_components,
        n_iter=num_iter,
        copy=True,
        check_input=True, 
        engine='auto',
        random_state=42)

    famd_model = famd.fit(X)
    transformed_X = famd_model.transform(X)
    
    my_model = linear_model.LinearRegression()
    
    my_model.fit(transformed_X,Y)

    return (my_model, famd_model)

cv_train = pd.read_csv('cv_training3.csv')

x_cols = [col for col in cv_train.columns if col != 'LogSalePrice']
print(x_cols)

X = cv_train[x_cols]

(my_model, famd_model) = get_trained_model_and_transform(X, 
                                                         cv_train['LogSalePrice'].values.ravel())

cv_validation = pd.read_csv('cv_validation3.csv')
transformed_X = famd_model.transform(X)
old_predictions = my_model.predict(transformed_X)
print(old_predictions.mean())

new_X = cv_validation[x_cols]

new_transformed_X = famd_model.transform(new_X)

new_predictions = my_model.predict(new_transformed_X)
print(new_predictions.mean()
)
```

The output is the following : 

```
['MSSubClass', 'LogGrLivArea', 'MSZoning']
12.0300579767497
11.946205619238583
```

The only difference between the 2 snippets, **is that we have wrapped the transform and model building to a function in the second whereas we have not done that in the first** (and the results are drastically different).

I am attaching the input data files here as well. Feel free to let me know if you need more information.

NOTE : For the sake of ease of testing, I have included both these snippets as two scripts (script1.py and script2.py ) in the attached folder. I have added a screenshot of the output on my mac terminal as well.

**However, I also tested these two scripts on an online python interface (https://repl.it/languages/python3) and they look to be giving identical outputs.** I am using the production version of prince module for these scripts and had to change my matplotlib backend to Agg on my mac to get this working on my mac. Would that be the reason for the different result ?

[data.zip](https://github.com/MaxHalford/prince/files/3040285/data.zip)

Thanks

**Comment by MaxHalford** [comment]
Are you sure? I just ran this and the second snippet returned the same output as the first one. By the way you can tell GitHub to use Python highlighting by using ````python` at the top of your snippet.

**Comment by babinu-uthup-4JESUS** [comment]
Hi @MaxHalford ,

I have updated my previous comment to include another example. However, as I have updated in my previous comment, there is an interesting observation : 


**Testing  these two scripts on an online python interface (https://repl.it/languages/python3) and gave dentical outputs**. I am using the production version of prince module for these scripts and had to change my matplotlib backend to Agg on my mac to get this working on my mac. Would that be the reason for the different result ?

**Comment by MaxHalford** [comment]
I just took a look and it seems that the parameter for the number of iterations, `n_iter`, is set to 10 in `script1.py` and to 20 in `script2.py`. It seems that this is the cause of the difference between both scripts.

**Comment by MaxHalford** [comment]
@babinu-uthup-4JESUS any news?
