### ISSUE TITLE
method CA : axis 2 inverted coordinate

### ISSUE THREAD

**Issue by loicmidy** [MaxHalford/prince#64]
Hello,
I just followed the tutorial for correspondance analysis and I found that the coordinates of points on axis 2 are inverted  : this can be seen when comparing the figure obtained with ca.plot_coordinates and the figure in the referenced textbook.
Ex : black hair has positive coordinate on axis 2 in the textbook and negative in the example.

Yours sincerely
Loïc Midy

**Comment by MaxHalford** [comment]
Hello,

This doesn't matter because the interpretation is symmetric. Actually what it is down to is the SVD implementation. You really don't have to worry about inverted axes.
