### ISSUE TITLE
MCA onehot handle unknown

### ISSUE THREAD

**Issue by DRL36** [MaxHalford/prince#66]
I'm trying to change the onehot encoder in your code by adding handle_unknown = 'ignore' in the super __init__(),  but I always get the error of __init__() got an unexpected keyword argument 'handle_unknown'. Any ideas on how to solve this?

**Comment by DRL36** [comment]
It's OK, i think I solved it.

**Comment by MaxHalford** [comment]
I love these kind of issues.

**Comment by pallavghose** [comment]
@DRL36 how did you solve it?
