### ISSUE TITLE
Generalized Procrustes Analysis (GPA)

### ISSUE THREAD

**Issue by MaxHalford** [MaxHalford/prince#68]
I would like to add [Generalized Procrustes Analysis](https://www.wikiwand.com/en/Generalized_Procrustes_analysis) to `prince`. It's quite useful for analyzing free-form surveys. I'll be storing some resources here while I work on it:

- [Procrustes analysis](http://www.indiana.edu/~g562/PBDB2013/Day%203A%20-%20Procrustes.pdf)
- [Procrustes, PCA, and 3D coordinates](http://www.indiana.edu/~g562/Lectures/Lecture%204%20-%20Procrustes,%20PCA,%20and%20morphospace.pdf)
- [(Generalized) Procrustes analysis with Python/NumPy](https://medium.com/@olga_kravchenko/generalized-procrustes-analysis-with-python-numpy-c571e8e8a421)
- [Procrustes Shape Analysis](http://www.cse.psu.edu/~rtc12/CSE586/lectures/cse586ShapeAndPCA.pdf)

**Comment by charlesincharge** [comment]
I need to perform GPA in Python for my own work, so I might take this up!
