### ISSUE TITLE
FAMD results discrepancies with boolean vs category variable

### ISSUE THREAD

**Issue by Melkaz** [MaxHalford/prince#69]
Hello,

I have a dataset composed of 8 numerical variables and a single category variable (0 or 1).

I'd like to perform a FAMD.

If I treat this category variable as a boolean, I obtain this plot of row coordinates:

![image](https://user-images.githubusercontent.com/1302218/60593169-78e44780-9da2-11e9-9289-6976b0eadad9.png)

When I enforce the variable as a category, I obtain this plot:

![image](https://user-images.githubusercontent.com/1302218/60593292-ba74f280-9da2-11e9-9490-1e880c3b563c.png)

An interactive demo is available here: https://repl.it/repls/DismalClientsideTheory

Is this expected ?
Thanks !

prince==0.6.3

**Comment by MaxHalford** [comment]
Hey @Melkaz,

I took a look at this and I believe the current API makes sense. If you treat a variable as a category, then it will be one-hot encoded and an MCA will be used. If the variable is treated as a boolean, then it treated as a numeric variable with two possible values, and a PCA will be used. Do you agree?

**Comment by Melkaz** [comment]
Yeah, I thought about it also and it makes sense.

Thanks :)
