### ISSUE TITLE
Multicollinearity

### ISSUE THREAD

**Issue by gilfinkelstein** [MaxHalford/prince#70]
When running the famd the model creates a column for each category within each categorical variable. For the best of my understanding, this creates a multicollinearity issue, as the created binary columns are perfectly correlated.

For example, assume that I have a gender column. The famd model will create a "male" column containing 1/0 and a "female" column containing 1/0. Those two columns are linearly correlated, as one is simply 1 - the other.

Am I missing something?

In sklearn hot one encoder there is a possibility to remove one of the columns. Is it possible to add this feature to the famd?

thank you
Gil

**Comment by MaxHalford** [comment]
Hey,

What you're mentioning also exists for MCA. I wouldn't worry about this, as one-hot encoding is standard practice in the factor analysis literature.
