### ISSUE TITLE
Visualization of data with different labels for MCA

### ISSUE THREAD

**Issue by shiwentao00** [MaxHalford/prince#71]
Hello,

I'm trying to use your MCA module to visualize my binary dataset. In your example, all the data points are grey. Is it possible to assign different colors to the data points according to their labels?

Thanks a lot!

**Comment by MaxHalford** [comment]
Hello,

No, that isn't possible as of now. Feel free to issue a pull request :)

**Comment by ScottishFold007** [comment]
I tried：
![image](https://user-images.githubusercontent.com/36957508/79965293-6d434800-84be-11ea-83b7-0e54ca94679c.png)

**Comment by macfernandez** [comment]
Hi! Is this issue still opened?
I wanted to do something similar and I made some modifications on my forked repo. 
Is it ok if a make a PR?

**Comment by MaxHalford** [comment]
PRs are always welcome :)
