### ISSUE TITLE
FAMD row_contributions

### ISSUE THREAD

**Issue by LNS98** [MaxHalford/prince#75]
I was trying use row_contributions on FAMD to recover the contributions of each individual column on the principal components, but it throws me an error. Wasn't sure if it is because it hasn't been built?

**Comment by MaxHalford** [comment]
Hey! Can you share some code?

**Comment by tomshaffner** [comment]
I sadly don't have the time to make a minimum reproducible example here, but I figured I'd at least note that I also am having the above issue and would flesh it out a bit with some details. The error I get is this:

`KeyError: "None of [Index(['outlet_id', 'rain_drizzle', 'prod_txt'], dtype='object')] are in the [columns]"`

Of note, those three columns are the only categorical variables in my code; apparently trying to pass them to row_contributions fails. A bit more detail about the example I'm using. The chunk of code that throws this error is here (note the commented conversion of the three categorical columns to strings; I tried that too but it didn't fix this):
`#!pip3 install prince
import prince

df=df.dropna()
y=df['total_quantity_sold']
headers_for_x = ['rain_drizzle','prod_txt','mean_temperature','min_temp','max_temp','precipitation','outlet_id','FRIDAY','SATURDAY','SUNDAY','isHolidayFlag','percent_ann_price','visibility','snow_depth', \
      'DayOfTheWeek','sold_last_year','sold_this_weekday_last_year','sold_yesterday']
X=df[headers_for_x]
string_cols = ['rain_drizzle','prod_txt','outlet_id']
#X[string_cols]=X[string_cols].astype(str)


#famd = prince.FAMD() #Factor analysis of mixed data - PCA for categorical and non-categorical data
famd = prince.FAMD(
     n_components=X.shape[1],
     n_iter=10,
     copy=True,
     check_input=True,
     engine='auto',       ## Can be "auto", 'sklearn', 'fbpca'
     random_state=42)
famd=famd.fit(X)

#famd.explained_inertia_
print(famd.row_contributions(X))`

Also, a printout of the dtypes of the X dataframe:
`
rain_drizzle                    object
prod_txt                        object
mean_temperature               float64
min_temp                       float64
max_temp                       float64
precipitation                  float64
outlet_id                       object
FRIDAY                           int64
SATURDAY                         int64
SUNDAY                           int64
isHolidayFlag                    int64
percent_ann_price              float64
visibility                     float64
snow_depth                     float64
DayOfTheWeek                     int64
sold_last_year                   int64
sold_this_weekday_last_year      int64
sold_yesterday                   int64
dtype: object`

Know that's not a lot more helpful than the above, but hopefully better than a complete lack of an error message like the original report had.

**Comment by tomshaffner** [comment]
Another quick followup on this. After a glance at the code it appears the famd basically splits the dataframe and performs a pca and an mca for numeric and categorical variables respectively. And looking at mca (and ca, which it calls) I don't immediately see a row_contributions property (at least not in the readme documentation). So I'm wondering if in fact this property just isn't available for famd? Or if so, if the function call in famd should be applied only to the numeric/pca portion of the dataset.

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
