### ISSUE TITLE
Incorrect Normalization

### ISSUE THREAD

**Issue by borr** [MaxHalford/prince#76]
```
if self.normalize:
    # Scale continuous variables to unit variance
    num = X.select_dtypes(np.number).columns
    normalize = lambda x: x / np.sqrt((x ** 2).sum() or 1)
    X.loc[:, num] = (X.loc[:, num] - X.loc[:, num].mean()).apply(normalize, axis='rows')
```
This will result in zero mean but **not** unit variance, for which one needs to divide by standard deviation. Correct version something like:
```
if self.normalize:
    # Scale continuous variables to unit variance
    num = X.select_dtypes(np.number).columns
    n_samp = X.shape[0]
    normalize = lambda x: x / (np.sqrt((x ** 2).sum()/n_samp) or 1)
    X.loc[:, num] = (X.loc[:, num] - X.loc[:, num].mean()).apply(normalize, axis='rows')
```

**Comment by MaxHalford** [comment]
The normalization in `FAMD` doesn't necessarily result in unit variance. It's a different kind of normalization. See [this](https://personal.utdallas.edu/~herve/Abdi-MFA2007-pretty.pdf) paper. I'll try to make things clearer in the code comments.

**Comment by borr** [comment]
I see, but what is not clear in the paper is incorporating categorical variables. AFAIK prince uses dummy coding but is there any additional normalization that accounts for category frequencies?
