### ISSUE TITLE
Overlapping category text- with possible solution

### ISSUE THREAD

**Issue by MrRobot2211** [MaxHalford/prince#77]
Hi thank you for your package it was really useful , and I see there is very little development in categorical variable analysis in python compared to R. I have tweaked some of the plot functions so as to get non-overlapping text when rou plot column or row labels.  I would like to  contribute my code, are you open to receiving it?

**Comment by MaxHalford** [comment]
Hey @MrRobot2211, that's really kind of you! The usual way to proceed is to fork the repository and make a pull request. If this is something that you're familiar with then maybe we can figure something else out. For starters, do you have a screenshot of the result?

**Comment by MaxHalford** [comment]
Any progress @MrRobot2211?

**Comment by MrRobot2211** [comment]
I will be probably uploading my solution this weekend.  Sorry for the
delay.

**Comment by MaxHalford** [comment]
Don't be sorry! There's no worry :)

**Comment by keremnernekli** [comment]
Hello, is this still an ongoing issue if so, I think I can help.
