### ISSUE TITLE
Plots in README are empty

### ISSUE THREAD

**Issue by MaximeKan** [MaxHalford/prince#79]
Hi @MaxHalford,

I love this package! Thanks for your amazing work on it.
Just wanted to draw your attention to the fact that the plots in the README are all empty now. This might be due to your last commits because I remember seeing them still a couple of days ago.

Cheers,

Maxime

**Comment by MaxHalford** [comment]
Damn you're right... I'll fix it ASAP.

**Comment by MaxHalford** [comment]
Okay it should be fixed now :). Some images are still white for me but I think it's because of the cache on GitHub's side.
