### ISSUE TITLE
TypeError: must be type, not classobj (in Python 2.7)

### ISSUE THREAD

**Issue by arima-sambunath** [MaxHalford/prince#8]
Here is my code 
import matplotlib.pyplot as plt
import pandas as pd
from prince import MCA

df = pd.read_csv('data/ogm.csv')
mca = MCA(df, n_components=-1)

Exception 
--------------------

TypeError             Traceback (most recent call last)
<ipython-input-21-5b3435e730c8> in <module>()
      4 
      5 df = pd.read_csv('data/ogm.csv')
----> 6 mca = MCA(df, n_components=-1)

/home/sambhu/env-attrition/local/lib/python2.7/site-packages/prince-0.2.6-py2.7.egg/prince/mca.pyc in __init__(self, dataframe, n_components, use_benzecri_rates, plotter)
     40         )
     41 
---> 42         super(MCA, self).__init__(
     43             dataframe=pd.get_dummies(dataframe),
     44             n_components=n_components,

TypeError: must be type, not classobj

**Comment by KaiHuangMO** [comment]
No any solution??

**Comment by MaxHalford** [comment]
The library is only available for Python 3!

**Comment by GoingMyWay** [comment]
@MaxHalford same issue.

**Comment by emrahy16** [comment]
add object to Base class. 

Base(object) :
....

**Comment by MaxHalford** [comment]
I'm closing this issue and others mentionning Python 2. **Prince only supports Python 3**.
