### ISSUE TITLE
Transform problem in last version (0.6.4)

### ISSUE THREAD

**Issue by wayfarer91-tog** [MaxHalford/prince#81]
Hello.

First of all, thanks for this great tool.

I noticed a bug when trying to transform using version 0.6.4. When:

```
import prince

nc = int(X_train.shape[1] * 0.1)

famd = prince.FAMD(n_components=2, n_iter=3, copy=True, check_input=True, engine='auto', random_state=0).fit(X_train)

X_train, X_test = famd.transform(X_train), famd.transform(X_test)
```
Triggers an error: 

`TypeError: check_is_fitted() missing 1 required positional argument: 'attributes'
`

I downgraded to 0.6.0 and the error is gone.

Thanks!

**Comment by MaxHalford** [comment]
That's actually because your `scikit-learn` version is out-of-date. I'll update `setup.py` to enforce having the latest version.

Thanks for raising the issue!
