### ISSUE TITLE
utils.validation.check_is_fitted(self) is giving errors

### ISSUE THREAD

**Issue by munkim** [MaxHalford/prince#82]
I am using 0.21.0 version of sklearn.

I am following the tutorial on Readme for PCA exactly, but it is giving me the following error.

>>> X, y = datasets.load_iris(return_X_y=True)
>>> X = pd.DataFrame(data=X, columns=['Sepal length', 'Sepal width', 'Petal length', 'Petal width'])
>>> y = pd.Series(y).map({0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'})
>>> X.head()
   Sepal length  Sepal width  Petal length  Petal width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
>>> 
>>> 
>>> X
     Sepal length  Sepal width  Petal length  Petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
>>> 
>>> pca = prince.PCA(
...     n_components=2,
...     n_iter=3,
...     rescale_with_mean=True,
...     rescale_with_std=True,
...     copy=True,
...     check_input=True,
...     engine='auto',
...     random_state=42
... )
>>> pca = pca.fit(X)
>>> 
>>> pca.transform(X).head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mun/anaconda3/envs/ofried/lib/python3.7/site-packages/prince/pca.py", line 86, in transform
    utils.validation.check_is_fitted(self)
TypeError: check_is_fitted() missing 1 required positional argument: 'attributes'

**Comment by MaxHalford** [comment]
Hey there, can you try again with the latest version of prince, which is `0.6.5`?

**Comment by colibrisson** [comment]
I encounter the same problem with 0.6.5

**Comment by MaxHalford** [comment]
What about if you install the latest version of `sklearn`?

**Comment by colibrisson** [comment]
I was using scikit-learn 0.21.3 but when I installed Prince yesterday, pip changed it to version 0.22.1. Here is the pip ourput:

`Installing collected packages: scikit-learn, prince
  Found existing installation: scikit-learn 0.21.3
    Uninstalling scikit-learn-0.21.3:
      Successfully uninstalled scikit-learn-0.21.3
Successfully installed prince-0.6.5 scikit-learn-0.22.1`

**Comment by iegorval** [comment]
I have the same problem with FAMD. I get `TypeError: check_is_fitted() missing 1 required positional argument: 'attributes'` on any action with FAMD after fitting.

**Comment by MaxHalford** [comment]
Hello! Try installing version `0.6.3`. I'm actually going to delete releases `0.6.4` and `0.6.5` and upload a new version with some fixes.

**Comment by colibrisson** [comment]
Thanks!

**Comment by cemcdaniel** [comment]
Hi, can someone give me the exact syntax of the install for this version.  I used the following and I think it defaults to the latest version.

conda install prince-factor-analysis

**Comment by MaxHalford** [comment]
Hey @cemcdaniel, try `pip install prince==0.6.3`.

**Comment by MaxHalford** [comment]
Version 0.7 has been released, hopefully it fixes this bug.

**Comment by ANFANGERMI** [comment]
I encounter the same error in version 0.7

**Comment by MaxHalford** [comment]
This should be fixed with version 0.7.1.
