### ISSUE TITLE
Is it possible to filter the points on the graphic according to cos2

### ISSUE THREAD

**Issue by Frenchyy1** [MaxHalford/prince#83]

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
