### ISSUE TITLE
OneHotEncoder constructor returning TypeError on fit function

### ISSUE THREAD

**Issue by ixioph** [MaxHalford/prince#84]
This one's been dragging me through the mud. I just installed prince to make use of the MCA, but I consistently get the following error when calling the fit() function: 

`TypeError: __init__() got an unexpected keyword argument 'categories'`

I'm pulling the example directly from the mca section of the README. I've tried manipulating one_hot.py directly, but nothing seems to yield any results. Here is the problematic snippet: 

```
mca = prince.MCA(
    n_components=2, 
    n_iter=3, 
    copy=True,
    check_input=True,
    engine='auto',
    random_state=42
)
mca = mca.fit(test_df) # errors here
mca.fit() 
```

**Comment by MaxHalford** [comment]
Hello! Try installing version `0.6.3`. I'm actually going to delete releases `0.6.4` and `0.6.5` and upload a new version with some fixes.

**Comment by ixioph** [comment]
That did the trick, thanks!

**Comment by ankur-chouragade** [comment]
Getting the following error, even when I installed  `0.6.3` release
`TypeError: SparseDataFrame() takes no arguments`

**Comment by lrusso96** [comment]
> Getting the following error, even when I installed `0.6.3` release
> `TypeError: SparseDataFrame() takes no arguments`

Updating to `0.6.5` worked for me. It is due to backwards incompatible changes of [SparseDataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html).

Hope it helps.

**Comment by ankur-chouragade** [comment]
0.6.5 throws the same error.
