### ISSUE TITLE
Optimize the visualization of analytical results

### ISSUE THREAD

**Issue by ScottishFold007** [MaxHalford/prince#88]
This python library is awesome, but it's prone to overlap when there's a high volume.
I've tried some ways to improve it, whether it's possible to add in？

![image](https://user-images.githubusercontent.com/36957508/79964747-b646cc80-84bd-11ea-815f-6b18f5d59107.png)

**Comment by MaxHalford** [comment]
That looks great! You're welcome to make a pull request so that I can review the changes :)
