### ISSUE TITLE
calculate MCA cos2 and result comparability with MCA library

### ISSUE THREAD

**Issue by emilienschultz** [MaxHalford/prince#89]
I meet some difficulties to compare MCA results between Prince and MCA library, especially to calculate cos2. There is a ratio difference on each component : is there any reason ?
(am I wrong to use the ratio of factor square on squared row norms (cos2(r,c) = F(r,c)**2/||r||**2 for r the row and c the component - in my case I have cos2>1, so kind of wrong).

**Comment by MaxHalford** [comment]
Our implementation is probably wrong! I say "probably" because it's not something I've tested very thoroughly. I would love to see a pull request with a correction.

**Comment by emilienschultz** [comment]
I compared with R package (FactoMineR), the implementation of ACM is great, no difference
I am looking on how to calculate cos2 for an MCA (seems different to PCA). If you have any docs on it, I would try to implement it.

**Comment by MaxHalford** [comment]
Actually it's difficult to find a reliable reference... I had bookmarked [this](https://personal.utdallas.edu/~herve/Abdi-MCA2007-pretty.pdf) but it seems to have expired. Maybe a way to proceed is to look into the FactoMineR source code, but it's difficult to read.

**Comment by emilienschultz** [comment]
I contacted one of the developper (François Husson), I am expecting his answer.

**Comment by emilienschultz** [comment]
He told me that its the same as PCA, factor squared on norm squared of the row. But when I tried, I needed to use the row norm in the projected space (a complete decomposition) to get the same result as R. Make sens for you ? I will dig a little more before suggesting something

**Comment by MaxHalford** [comment]
I think I see what you mean. I remember that many things weren't very clear when I first implemented Prince. It's always nice to have some fresh (and motivated!) eyes to take a look at the details. After my PhD, which should be over by this summer, I'm planning to take a few days to sort some things out in Prince. I suppose we can assume that FactoMineR can be used as a groun truth and we should aim to reproduce their outputs.

Thanks for digging into this! It will benefit many people to have a clear implementation of details such as this.

**Comment by emilienschultz** [comment]
Hi. Yes I would be glad to join you to expand you library. I am finishing a
introduction book for social scientists in French, and I introduce your
library I found the most convenient to use for MCA and CA. For the moment,
I just present how to calculate cos2 directly with the result of prince,
because I am not enough confident with the efficiency of my code to pull
request it. I do the complete decomposition of the matrix in the factor
space, and then I calculate the distance square of the vector. I don't know
how to calculate it before the MCA, because it seems to change... Good luck
for writing your PhD. When will you finish ?
Emilien

**Comment by MaxHalford** [comment]
No worries! I'll try to iron out some details during the upcoming summer. I should be done with the PhD by the end of September.
