### ISSUE TITLE
How to change colors of plot_row_coordinates?

### ISSUE THREAD

**Issue by insuquot** [MaxHalford/prince#90]
Using famd.plot_row_coordinates, how can I change the colors of each group specified in color_labels?

**Comment by jeanbaptisteb** [comment]
famd.plot_row_coordinates is a [matplotlib](https://matplotlib.org/index.html) object, so generally you can use that to customize the plot as you want.
 
Assuming your plot has two colors that you don't like, and you want to change them for two others (let's say green and black), you can add the following code before callingfamd.plot_row_coordinates:
```
import matplotlib as mpl
mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=["green", "black"])
```
for three colors:

```
mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=["green", "black", "cyan"])
```
etc.

Note that this will change the default colors for all the subsequent plots in your script, so you have to call mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=.....) each time you want to use different colors for a new plot. 

There may be other ways to do it, but I haven't investigated too much. Maybe you'll get more answers on StackOverflow, many people there are very knowledgeable about Matplotlib.

**Comment by jeanbaptisteb** [comment]
> 
> 
> Using famd.plot_row_coordinates, how can I change the colors of each group specified in color_labels?

@insuquot famd.plot_row_coordinates is a [matplotlib](https://matplotlib.org/index.html) object, so generally you can use that to customize the plot as you want.
 
Assuming your plot has two colors that you don't like, and you want to change them for two others (let's say green and black), you can add the following code before callingfamd.plot_row_coordinates:
```
import matplotlib as mpl
mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=["green", "black"])
```
for three colors:

```
mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=["green", "black", "cyan"])
```
etc.

Note that this will change the default colors for all the subsequent plots in your script, so you have to call mpl.rcParams['axes.prop_cycle'] = mpl.cycler(color=.....) each time you want to use different colors for a new plot. 

There may be other ways to do it, but I haven't investigated too much. Maybe you'll get more answers on StackOverflow, many people there are very knowledgeable about Matplotlib.

**Comment by MaxHalford** [comment]
Thanks for answering @jeanbaptisteb. Indeed the plotting method from `prince` returns Matplotlib objects, which allows you to customize them yourself.
