### ISSUE TITLE
ERROR: 'prince' has no attribute 'MCA'

### ISSUE THREAD

**Issue by Aakaash-5** [MaxHalford/prince#91]
I am not able to use MCA in my notebook
The above error pops up

**Comment by MaxHalford** [comment]
Can you at least provide a traceback of the error? Please take a minute to put yourself in my shoes: I'm not a magician and I can't magically guess what the problem is.

**Comment by Aakaash-5** [comment]
Yeah I am sorry,
I am new to this kind of issue posting. Anyway here is the information.
Another thing I started working after reinstalling and it didn't give this kind of error.
I don't know why there was this error earlier but I'll put this information here and if you could see the reason behind this error, please check. 

AttributeError                            Traceback (most recent call last)
<ipython-input-112-272067e4b9e3> in <module>
      7 print(X.head())
      8 
----> 9 mca = prince.MCA()

AttributeError: module 'prince' has no attribute 'MCA'

**Comment by MaxHalford** [comment]
Yes it's probably due to a bad installation.

**Comment by RoboTums** [comment]
I had this issue when I installed prince with ``  conda install -c bioconda prince ``, which was the wrong package entirely. Easiest way I found to fix this was by
1. `` conda skeleton pypi prince ``
2. `` conda build prince ``
