### ISSUE TITLE
How to link column names and explained_inertia

### ISSUE THREAD

**Issue by neramas1221** [MaxHalford/prince#93]
Hi there I’m using the prince FAMD function on some custom data, I want to know what the first 10 components are in the famd.explained_inertia as column names, but I can’t seem to do that. I’ve tried using column correlations but that returns column names as the index plus some categorical values like, sex_male. Is there something I’m missing? 

Thank you for any help

**Comment by neramas1221** [comment]
Don’t worry someone explained to me what is happening and I was miss understanding something about the process. Sorry about that.

**Comment by neramas1221** [comment]
Don’t worry someone explained to me what is happening and I was miss understanding something about the process. Sorry about that.

**Comment by SadafGharaati** [comment]
Hi, I am having the same situation, would it be possible for you to help me in this regard?

**Comment by MaxHalford** [comment]
Hello there 👋

I apologise for not answering earlier. I was not maintaining Prince anymore. However, I have just refactored the entire codebase. This refactoring should have fixed many bugs.

I don’t have time and energy to check if this fixes your issue, but there is a good chance it does. Feel free to reopen this issue if the problem persists after installing the new version — that is, version 0.8.0 and onwards.
