### ISSUE TITLE
__init__() got an unexpected keyword argument 'check_input'

### ISSUE THREAD

**Issue by logisticregress** [MaxHalford/prince#98]
Hello, 
when running the basic example from the github page I get the following errors:

famd = prince.FAMD(n_components=2,n_iter=3,copy=True,check_input=True,engine='auto',random_state=42)

----> 1 famd = prince.FAMD(n_components=2,n_iter=3,copy=True,check_input=True,engine='auto',random_state=42)
TypeError: __init__() got an unexpected keyword argument 'check_input'

then: 
famd.fit(X) results with: SparseDataFrame() takes no arguments

Prince version 0.4.10
Pandas version 1.1.2
numpy version 1.18.5

**Comment by MaxHalford** [comment]
Can you upgrade your prince version? Version 0.4.10 is really old.
